version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filmapik-api
    ports:
      - "80:8080"  # Port 80 untuk produksi
    environment:
      - RUST_LOG=info
      - FILMAPIK_URL=https://filmapik.cam
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - CACHE_TTL_MOVIES=1800
      - CACHE_TTL_DETAILS=3600
      - CACHE_TTL_GENRES=86400
      - CACHE_TTL_COUNTRIES=86400
      - CACHE_CAPACITY=5000  # Kapasitas cache lebih besar untuk produksi
    volumes:
      - ./cache:/app/cache
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/movie/latest"]
      interval: 1m
      timeout: 10s
      retries: 3

  # Nginx reverse proxy untuk HTTPS (bila diperlukan)
  # web:
  #   image: nginx:alpine
  #   container_name: filmapik-web
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   depends_on:
  #     - api
  #   restart: always 