version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.nightly
    container_name: filmapik-api
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - FILMAPIK_URL=https://filmapik.cam
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/movie/latest"]
      interval: 1m
      timeout: 10s
      retries: 3 